let lrCatalog=[],lrSelected=localStorage.getItem('qc.library')||'',lrFilter='all',lrPage=0,lrRows=[],libraryVersion=0,compareData=null;
function datasetName(d){return `${d.name} · ${d.episodes} 条`}
async function renderLibrary(){
 const version=++libraryVersion;try{
 if(!lrCatalog.length)lrCatalog=(await api('/library/datasets')).datasets;
 if(page!=='lerobot'||version!==libraryVersion)return;
 if(!lrCatalog.some(d=>d.id===lrSelected))lrSelected=lrCatalog[0]?.id||'';
 const data=lrSelected?await api(`/library/${lrSelected}/episodes`):null;
 if(page!=='lerobot'||version!==libraryVersion)return;
 lrRows=data?.episodes||[];let shown=lrRows.filter(e=>lrFilter==='all'||e.grade===lrFilter||(lrFilter==='excluded'&&e.excluded)||(lrFilter==='pending'&&!e.review));const pages=Math.max(1,Math.ceil(shown.length/50));lrPage=Math.min(lrPage,pages-1);
 $('#library-content').innerHTML=`<section class="panel"><div class="toolbar"><label class="grow">LeRobot 数据集<select id="lr-dataset">${lrCatalog.map(d=>`<option value="${esc(d.id)}" ${d.id===lrSelected?'selected':''}>${esc(datasetName(d))}</option>`).join('')||'<option>暂无 LeRobot 数据</option>'}</select></label><button id="lr-refresh">刷新</button></div><p class="path">${esc(data?.dataset.root||'自动读取本系统导出及 /data 下的 LeRobot 数据')}</p><details><summary>打开其他 LeRobot 目录</summary><form id="lr-discover-form" class="inline-form"><input id="lr-discover-root" placeholder="含 LeRobot 数据集的目录" required><button>读取目录</button></form></details></section>
 <section class="panel"><div class="toolbar"><h2>回放与人工复筛</h2><button id="lr-export" class="primary" ${!lrRows.some(e=>e.review)?'disabled':''}>生成复筛副本</button></div><p class="note">A / B 可保留，F 自动排除。保存后再生成副本，原数据保留。</p><div class="counts"><span><strong>${lrRows.length}</strong>条记录</span><span><strong>${lrRows.filter(e=>e.review).length}</strong>已复筛</span><span><strong>${lrRows.filter(e=>e.excluded).length}</strong>已排除</span></div><label>筛选<select id="lr-filter">${[['all','全部记录'],['pending','未复筛'],['A','A'],['B','B'],['F','F'],['excluded','已排除']].map(([v,l])=>`<option value="${v}" ${v===lrFilter?'selected':''}>${l}</option>`).join('')}</select></label><div class="overflow"><table><thead><tr><th><input type="checkbox" id="lr-select-all" aria-label="选中本页"></th><th>记录</th><th>等级</th><th>复筛</th><th>原因</th><th></th></tr></thead><tbody>${shown.slice(lrPage*50,(lrPage+1)*50).map(e=>`<tr><td><input class="lr-pick" type="checkbox" value="${e.episode_index}" aria-label="选中记录 ${e.episode_index}"></td><td>episode_${String(e.episode_index).padStart(6,'0')}<div class="note">${e.length} 帧</div></td><td>${badge(e.grade)}</td><td>${e.excluded?'已排除':e.review?'已复筛':'未复筛'}</td><td class="reason">${esc(e.review?.reason||'')}</td><td><button data-lr-episode="${e.episode_index}">回放 / 复筛</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">没有匹配的记录</td></tr>'}</tbody></table></div><div class="pagination"><span>第 ${lrPage+1} / ${pages} 页</span><button id="lr-prev" ${lrPage===0?'disabled':''}>上一页</button><button id="lr-next" ${lrPage+1===pages?'disabled':''}>下一页</button></div><details><summary>批量标注选中记录</summary><form id="lr-bulk-form" class="bulk-form"><label>等级<select id="lr-bulk-grade"><option>B</option><option>A</option><option>F</option></select></label><label>操作人<input id="lr-bulk-actor" value="${esc(localStorage.getItem('qc.actor')||'')}" required></label><label class="grow">原因<input id="lr-bulk-reason" required></label><button class="primary">保存选中记录</button></form></details><div id="lr-export-result"></div></section>`;
 $('#lr-dataset').onchange=e=>{lrSelected=e.target.value;localStorage.setItem('qc.library',lrSelected);lrPage=0;renderLibrary()};
 $('#lr-refresh').onclick=()=>{lrCatalog=[];renderLibrary()};$('#lr-filter').onchange=e=>{lrFilter=e.target.value;lrPage=0;renderLibrary()};$('#lr-prev').onclick=()=>{lrPage--;renderLibrary()};$('#lr-next').onclick=()=>{lrPage++;renderLibrary()};
 $('#lr-select-all').onchange=e=>$$('.lr-pick').forEach(c=>c.checked=e.target.checked);
 $$('[data-lr-episode]').forEach(b=>b.onclick=async()=>{try{const e=await api(`/library/${lrSelected}/episodes/${b.dataset.lrEpisode}`);populateEpisode({...e,kind:'lerobot',data:{}})}catch(e){toast(e.message)}});
 $('#lr-discover-form').onsubmit=async e=>{e.preventDefault();try{const d=await api('/library/discover',{method:'POST',body:JSON.stringify({root:$('#lr-discover-root').value})});lrCatalog=[...new Map([...lrCatalog,...d.datasets].map(d=>[d.id,d])).values()];lrSelected=d.datasets[0]?.id||lrSelected;toast(`找到 ${d.datasets.length} 个数据集`);renderLibrary()}catch(err){toast(err.message)}};
 $('#lr-bulk-form').onsubmit=async e=>{e.preventDefault();const ids=$$('.lr-pick:checked').map(c=>Number(c.value));if(!ids.length){toast('请先勾选记录');return}const actor=$('#lr-bulk-actor').value;try{await api(`/library/${lrSelected}/review`,{method:'POST',body:JSON.stringify({annotations:ids.map(i=>({episode_index:i,grade:$('#lr-bulk-grade').value,excluded:false,reason:$('#lr-bulk-reason').value,actor,revision:lrRows.find(e=>e.episode_index===i)?.review?.revision||0}))})});localStorage.setItem('qc.actor',actor);toast('批量复筛已保存');renderLibrary()}catch(err){toast(err.message)}};
 $('#lr-export').onclick=async e=>{const button=e.target;button.disabled=true;$('#lr-export-result').textContent='正在生成并校验复筛副本…';try{const result=await api(`/library/${lrSelected}/export`,{method:'POST'});lrCatalog.push(result.dataset);$('#lr-export-result').innerHTML=`<p>已生成 ${result.output_episodes} 条，排除 ${result.excluded} 条</p><div class="export-path">${esc(result.output)}</div><button id="open-reviewed">打开复筛副本</button>`;$('#open-reviewed').onclick=()=>{lrSelected=result.dataset.id;localStorage.setItem('qc.library',lrSelected);renderLibrary()}}catch(err){$('#lr-export-result').textContent=err.message}finally{button.disabled=false}};
 }catch(e){toast(e.message);$('#library-content').innerHTML='<section class="panel error-text">'+esc(e.message)+'</section>'}
}
async function renderCompare(){
 if($('#comparison-form'))return;
 $('#compare-content').innerHTML=`<section class="panel"><h2>选择仿真与真机 LeRobot 数据</h2><p class="note">复用旧版对比规则，按选中的机器人核对维度、单位、提示词和动作分布。</p><form id="comparison-form"><div class="settings-grid"><label>仿真数据目录<input id="sim-root" value="${esc(localStorage.getItem('qc.sim-root')||'/data/sim_data')}" required></label><label>真机数据目录<input id="real-root" value="${esc(localStorage.getItem('qc.real-root')||'/home/robot/dataqc/exports')}" required></label><label>机器人<select id="compare-robot"><option value="zerith">零次方 · 23维</option><option value="aloha">松灵 · 原版规则</option></select></label><label>每个数据集检查记录数<input id="compare-count" type="number" min="1" max="200" value="20"></label></div><p><button type="submit">读取两侧目录</button><button type="button" id="compare-analyze" class="primary" disabled>开始对比</button></p></form><div id="compare-selection"></div><p id="compare-status" class="note"></p></section><section id="comparison-result" class="panel" hidden></section>`;
 let selections=[];
 $('#comparison-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{selections=[];for(const [id,platform]of [['sim-root','simulation'],['real-root','real']]){const root=$('#'+id).value;localStorage.setItem('qc.'+id,root);const result=await api('/library/discover',{method:'POST',body:JSON.stringify({root})});selections.push(...result.datasets.map(d=>({...d,platform})))}$('#compare-selection').innerHTML=`<div class="overflow"><table><thead><tr><th>选择</th><th>来源</th><th>数据集</th><th>记录数</th></tr></thead><tbody>${selections.map((d,i)=>`<tr><td><input type="checkbox" class="compare-pick" value="${i}" checked></td><td>${d.platform==='simulation'?'仿真':'真机'}</td><td class="path">${esc(d.root)}</td><td>${d.episodes}</td></tr>`).join('')}</tbody></table></div>`;$('#compare-analyze').disabled=!selections.length;$('#compare-status').textContent=`找到仿真 ${selections.filter(d=>d.platform==='simulation').length} 组、真机 ${selections.filter(d=>d.platform==='real').length} 组。${selections.some(d=>d.platform==='simulation')?'':'仿真目录内未发现 LeRobot v2 数据，可更换目录。'}`}catch(err){toast(err.message)}finally{button.disabled=false}};
 $('#compare-analyze').onclick=async e=>{const selected=$$('.compare-pick:checked').map(c=>selections[Number(c.value)]);if(!selected.length){toast('请选择数据集');return}e.target.disabled=true;$('#compare-status').textContent='正在读取 Parquet 并对比…';try{compareData=await api('/compare/analyze',{method:'POST',body:JSON.stringify({datasets:selected.map(d=>({path:d.root,platform:d.platform})),robot_type:$('#compare-robot').value,max_episodes:Number($('#compare-count').value),max_frames:1000,stationary_threshold:40})});showComparison(compareData);$('#compare-status').textContent='对比完成'}catch(err){$('#compare-status').textContent=err.message}finally{e.target.disabled=false}};
}
function showComparison(r){
 const root=$('#comparison-result');root.hidden=false;
 const fmt=v=>{if(!v||!Object.keys(v).length)return '无数据';if(v.p01!=null)return `${Number(v.p01).toFixed(4)} ～ ${Number(v.p99).toFixed(4)}`;return JSON.stringify(v)};
 root.innerHTML=`<div class="toolbar"><h2>对比结果 ${badge(r.summary.status)}</h2><a href="/auto/api/compare/reports/${r.id}">下载报告</a></div><p class="note">仿真 ${r.summary.simulation_count} 组 / 真机 ${r.summary.real_count} 组 · 每组最多检查 ${r.sampling.max_episodes_per_dataset||$('#compare-count').value} 条；未抽中的记录不视为已检查。</p><details open><summary>Action / State 分布（P01～P99）</summary><div class="overflow"><table><thead><tr><th>向量</th><th>关节</th><th>仿真</th><th>真机</th><th>结果 / 原因</th></tr></thead><tbody>${(r.dimensions||[]).map(d=>`<tr><td>${esc(d.vector)}</td><td>${esc(jointLabel(d.name||d.canonical||String(d.index)))}</td><td>${esc(fmt(d.simulation))}</td><td>${esc(fmt(d.real))}</td><td>${badge(d.status)} ${esc((d.reasons||d.warnings||[]).join('；'))}</td></tr>`).join('')}</tbody></table></div></details><details><summary>提示词格式 ${badge(r.prompts.status)}</summary><p>${esc(r.prompts.standard||'比较任务模板与操作顺序')}</p><p class="warning-text">${esc((r.prompts.warnings||[]).join('；'))}</p>${(r.prompts.formats||[]).map(f=>`<div class="check-row">${esc(f.template)} ${badge(f.status||'pass')}</div>`).join('')}</details><details><summary>检查与异常详情（${(r.issue_details||[]).length}）</summary>${(r.issue_details||[]).map(d=>`<div class="check-row"><b>${esc(d.project||d.target)}</b> ${badge(d.status)}<p>${esc(d.reason)}</p><div class="path">${(d.datasets||[]).map(v=>esc(v.path||v.name)).join('<br>')}</div></div>`).join('')||'<p>未发现异常。</p>'}</details>`;
}
